settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: logour
  path: .
  commands: 
    install:
      status: true
      method: make build
    run:
      status: true
      method: ./logour
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
